# Generated by Django 3.2.9 on 2021-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='guest_user', max_length=200, verbose_name='username'),
        ),
    ]
