# Generated by Django 3.2.9 on 2021-12-23 17:13

from django.db import migrations
import multiselectfield.db.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userprofile',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'Seller'), ('C', 'Customer')], default=[], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=users.models.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
