# Generated by Django 3.2.9 on 2021-12-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_sellerinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerinformation',
            options={'verbose_name': 'Seller Detail', 'verbose_name_plural': 'Seller Details'},
        ),
    ]
