# Generated by Django 3.2.9 on 2021-12-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_sellerinformation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerinformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='SellerInformation',
        ),
    ]
