# Generated by Django 3.2.9 on 2021-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('SA', 'Stock Available'), ('NSA', 'No Stock Available')], default='SA', max_length=3)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
