# Generated by Django 3.2.9 on 2021-12-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Ordered Product', 'verbose_name_plural': 'Ordered Products'},
        ),
    ]
