# Generated by Django 3.2.9 on 2021-12-07 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_wishlistproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist_users',
            field=models.ManyToManyField(related_name='product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WishlistProduct',
        ),
    ]
