# Generated by Django 3.2.9 on 2021-12-07 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0014_auto_20211207_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wishlist_users',
            field=models.ManyToManyField(related_name='wishlist_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
