# Generated by Django 3.2.9 on 2021-12-09 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_auto_20211209_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='wishlist_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlist_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
