# Generated by Django 3.2.9 on 2022-01-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20220108_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='ordering_date',
        ),
    ]
